# default multipart config
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true

# default logger config
logging:
  level:
    root: info
    springfox.documentation: warn
    org.springframework: warn
    org.hibernate: warn
    org.thymeleaf: warn
    org.apache: warn
    org.quartz: warn
    io.swagger: warn
    org.zbus: warn
    sun.rmi: warn
  file: ./stdot.log

# default server config
server:
  port: 80
  servlet:
    context-path: /kbase-media

# default user converter config
convert:
  # Whether to enable the asynchronous interface
  enable-async: false
  # default output-folder
  outputFolder: /tmp/convert/
  outputFolder-async: /tmp/convert/async/
  video:
    vca:
      default: ffmpeg
      ffmpeg:
        # ffmpeg bin path
        path: /opt/ffmpeg/ffmpeg-3.0/
        toImage:
          fps: 0.2
  audio:
    # default asr tool
    asr:
      default: shhan
      # baidu is 60s/seg ; shhan is 20s/seg
      seg-duration: 20
      #baidu asr config
      baidu:
        appId: 11067243
        apiKey: iDEvPvY4zT9CzFgYKMQY6eAi
        secretKey: Wkeh8gIbB2LrNBtGwuechG8TUkLlB2TY
      shhan:
        base-url: http://172.16.8.103:8177/shRecBase/
  image:
    #default ocr tool
    ocr:
      default: abbyy
      #tencent youtu ocr tool config
      youtu:
        appId: 10125304
        secretId: AKIDVs45xejwtvmW5SpdkjYGpDUZTIwOp0Hn
        secretKey: a0EHCwgHhgnogMCvUr33uhKl195qSwip
        userId: 1071552744
      # abbyy fineReader engine config
      abbyy:
        path: /opt/ABBYY/FREngine11/Bin
        license: SWTT-1101-1006-4491-7660-4166